version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=gasto
      - MYSQL_ROOT_PASSWORD=messi2012
    ports:
      - '3306:3306'
    volumes:
      - ./db/script/data.sql:/docker-entrypoint-initdb.d/data.sql

volumes:
  test_vol:
    driver: local